// is this being loaded? doesn't seem like it
import autocompleteBinding from './autocompleteBinding'
import htmlValueBinding from './htmlValueBinding'
import contentEditable from './contentEditable'
import contenteditableSwitch from './contenteditableSwitch'
import numericFn from './numericFn'
import ddSlickAction from './ddSlickActionBinding'
import clickToEdit from './clickToEditBinding'
import datePicker from './datepickerBinding'
import dateTimePicker from './dateTimePickerBinding'
import dataTable from './datatableBinding'
import dynamicDataTable from './dynamicDatatableBinding'
import eventListener from './eventListenerBinding'
import selectOnFocus from './knockout.selectOnFocus'
import sortExtender from './sortExtender'
import bootstrapModal from './bootstrapModal'
import treemap from './treemapBinding'
import d3ChartBinding from './d3ChartBinding'
import tooltipBinding from './tooltipBinding'
import placeholderBinding from './placeholderBinding'
import titleBinding from './titleBinding'
import chart from './chart'
import bootstrapCollapsable from './bootstrapCollapsable'
import numericExtender from './numericExtender'
import childChangesExtender from './childChangesExtender'
import alphaNumericExtender from './alphaNumericExtender'
import i18nBinding from './i18nBinding'

