// is this being loaded? doesn't seem like it
define(function (require) {
  const autocompleteBinding = require('./autocompleteBinding')
  const htmlValueBinding = require('./htmlValueBinding')
  const contentEditable = require('./contentEditable')
  const contenteditableSwitch = require('./contenteditableSwitch')
  const numericFn = require('./numericFn')
  const ddSlickAction = require('./ddSlickActionBinding')
  const clickToEdit = require('./clickToEditBinding')
  const datePicker = require('./datepickerBinding')
  const dateTimePicker = require('./dateTimePickerBinding')
  const dataTable = require('./datatableBinding')
  const dynamicDataTable = require('./dynamicDatatableBinding')
  const eventListener = require('./eventListenerBinding')
  const selectOnFocus = require('./knockout.selectOnFocus')
  const sortExtender = require('./sortExtender')
  const bootstrapModal = require('./bootstrapModal')
  const treemap = require('./treemapBinding')
  const d3ChartBinding = require('./d3ChartBinding')
  const tooltipBinding = require('./tooltipBinding')
  const placeholderBinding = require('./placeholderBinding')
  const titleBinding = require('./titleBinding')
  const chart = require('./chart')
  const bootstrapCollapsable = require('./bootstrapCollapsable')
  const numericExtender = require('./numericExtender')
  const childChangesExtender = require('./childChangesExtender')
  const alphaNumericExtender = require('./alphaNumericExtender')
  const i18nBinding = require('./i18nBinding')
})
